cal/urls.py
from django.urls import path
from . import views


app_name = 'cal'
urlpatterns = [
    path('', views.CalendarView.as_view(), name="calendar"),
]

djangocalendar/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cal.urls')),
]

cal/models.py
from django.db import models

# Create your models here.
class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

cal/views.py
from datetime import datetime, timedelta
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from django.utils.safestring import mark_safe
import calendar
from datetime import date

from .utils import Calendar
from .models import Event

class CalendarView(generic.ListView):

    model = Event
    template_name = 'cal/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # use today's date for the calendar
        d = get_date(self.request.GET.get('month', None))

        # Instantiate our calendar class with today's year and date
        cal = Calendar(d.year, d.month)

        # Call the formatmonth method, which returns our calendar as a table
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)

        return context


def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()


def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month


def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month


def index(request):
    return HttpResponse('Hello')

cal/templates/cal/calendar.html
{% extends 'base.html' %}

{% block content %}
    <div class="clearfix">
        <a class="btn btn-info left" href="{% url 'cal:calendar' %}?{{ prev_month }}"> Өмнөх сар </a>
        <a class="btn btn-info right" href="{% url 'cal:calendar' %}?{{ next_month }}"> Дараагийн сар </a>
    </div>
    {{ calendar }}
{% endblock %}

djangocalendar/templates/base.html
{% load staticfiles %}

<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <title>Зар</title>
  </head>
  <body>
    <div class="container">
        <div class="main">
            {% block content %}

            {% endblock %}
        </div>
    </div>
  </body>
</html>